#
# Module manifest for module 'Office365Connect'
#
# Generated by: Philip Haglund
#
# Generated on: 2017-05-16
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Office365Connect.psm1'

# Version number of this module.
ModuleVersion = '1.5.0'

# ID used to uniquely identify this module
GUID = '80168612-0c36-42bd-9f69-e6a4eeda33d1'

# Author of this module
Author = 'Philip Haglund'

# Company or vendor of this module
CompanyName = 'Gonjer.com'

# Copyright statement for this module
Copyright = '(c) 2017 Philip Haglund. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell Module with two functions to connect and disconnect to all Office 365 services.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Connect-Office365','Disconnect-Office365')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'AzureAD', 'Office365', 'Connect', 'Msol', 'ExchangeOnline', 'Online'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PhilipHaglund/PowerShell/blob/master/Office365Connect/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PhilipHaglund/PowerShell/tree/master/Office365Connect'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/PhilipHaglund/PowerShell/master/Office365Connect/docs/pics/Office365Connect.jpg'

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/PhilipHaglund/PowerShell/blob/master/Office365Connect/ReleaseNotes.md'

        # Indicates this is a pre-release/testing version of the module.
        IsPrerelease = 'False'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/PhilipHaglund/PowerShell/master/Office365Connect/docs/about_Office365Connect.help.md'

}


